name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git submodule update --init --recursive
          ls ccsr
          cd port
          python -m pip install -r requirements.txt
          python setup.py
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: port/dist # The folder the action should deploy.
          repository-name: mattbruv/ccsr-port-test
          token: ${{ secrets.ACCESS_TOKEN }}
          force: true
          single-commit: true
